#!/bin/sh

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

OPTION_FILE=/etc/polipo/options
PPCTL=/usr/lib/polipo/polipo-control
test -x $PPCTL  || exit 0

# Exit if lo interface
[ "$METHOD" = "loopback" ] && exit 0

if [ -f $OPTION_FILE ] && \
	( grep -qsxi '^[[:blank:]]*method[[:blank:]]*any[[:blank:]]*$' $OPTION_FILE \
	|| grep -qsxi '^[[:blank:]]*method[[:blank:]]*ppp[[:blank:]]*$' $OPTION_FILE ) then
    $PPCTL go-online
fi

exit 0
